"""
Pydantic v2 models for the canonical business schema.

These models are the single source of truth for data validation across all
scrapers. Both Juanpa (gmaps) and Leo (instagram + directorios) must use
BusinessRaw to validate before inserting into businesses_raw.

Schema contract: docs/schema.md
DB contract:     db/migrations/001_create_schema.sql
"""

from __future__ import annotations

import re
from datetime import datetime
from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class SourceName(str, Enum):
    """Canonical source identifiers — must match sources.name in DB."""

    GMAPS = "gmaps"
    INSTAGRAM = "instagram"
    PAGINAS_AMARILLAS = "paginas_amarillas"
    MERCADO_LIBRE = "mercado_libre"


# ---------------------------------------------------------------------------
# Quality flags
# ---------------------------------------------------------------------------


class QualityFlag(str, Enum):
    """Allowed values for the quality_flags array field."""

    MISSING_PHONE = "missing_phone"
    MISSING_ADDRESS = "missing_address"
    LOW_CONFIDENCE_ADDRESS = "low_confidence_address"
    UNVERIFIED_COORDINATES = "unverified_coordinates"
    INACTIVE_INSTAGRAM = "inactive_instagram"
    DUPLICATE_CANDIDATE = "duplicate_candidate"


# ---------------------------------------------------------------------------
# Regex constants
# ---------------------------------------------------------------------------

_PHONE_E164_RE = re.compile(r"^\+57[0-9]{10}$")
_VALID_CITIES = {"Medellín", "Bogotá"}


# ---------------------------------------------------------------------------
# Main model
# ---------------------------------------------------------------------------


class BusinessRaw(BaseModel):
    """
    One row in businesses_raw — one business per source.

    Accepts dirty data from scrapers (partial normalisation is fine).
    All validators are lenient: they clean/coerce rather than hard-reject,
    except for fields where a wrong value would break Step 2 logic
    (city, phone_e164).
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        extra="forbid",
        use_enum_values=True,
    )

    # --- Identity ----------------------------------------------------------

    id: UUID | None = Field(
        default=None,
        description="PK generated by DB (uuid_generate_v4()). Leave None on insert.",
    )
    master_id: UUID | None = Field(
        default=None,
        description="Assigned by Step 2 entity-resolution. Null on raw insert.",
    )
    source: SourceName = Field(
        description="Origin of this row. Must be a valid SourceName.",
    )
    source_id: str = Field(
        description="Original ID from the source system (e.g. Google place_id).",
    )

    # --- Name --------------------------------------------------------------

    name: str = Field(
        description="Business name as it appears in the source, unmodified.",
    )
    name_normalized: str | None = Field(
        default=None,
        description=(
            "Lowercase, no accents, no legal suffixes (S.A.S., Ltda., S.A., E.U., Corp.). "
            "Scrapers may leave this None; Step 2 will fill it."
        ),
    )

    # --- Location ----------------------------------------------------------

    address_raw: str | None = Field(
        default=None,
        description="Full address string as scraped, unparsed.",
    )
    address_street: str | None = Field(
        default=None,
        description="Street/carrera and number only, extracted from address_raw.",
    )
    city: str = Field(
        description="Canonical city name. Only 'Medellín' or 'Bogotá' accepted.",
    )
    neighborhood: str | None = Field(
        default=None,
        description="Barrio or sector within the city.",
    )
    lat: float | None = Field(
        default=None,
        description="Latitude WGS-84.",
        ge=-90.0,
        le=90.0,
    )
    lng: float | None = Field(
        default=None,
        description="Longitude WGS-84.",
        ge=-180.0,
        le=180.0,
    )

    # --- Contact -----------------------------------------------------------

    phone_raw: str | None = Field(
        default=None,
        description="Phone number exactly as it appears in the source.",
    )
    phone_e164: str | None = Field(
        default=None,
        description="Normalised phone in E.164 format: +57 followed by 10 digits.",
    )
    whatsapp_flag: bool = Field(
        default=False,
        description=(
            "True if the source explicitly marks this number as WhatsApp "
            "or if a wa.me link was found."
        ),
    )

    # --- Instagram ---------------------------------------------------------

    instagram_handle: str | None = Field(
        default=None,
        description="Instagram username without the leading '@'.",
    )
    instagram_followers: int | None = Field(
        default=None,
        description="Follower count at scrape time.",
        ge=0,
    )
    instagram_posts_count: int | None = Field(
        default=None,
        description="Total published posts at scrape time.",
        ge=0,
    )
    instagram_last_post_at: datetime | None = Field(
        default=None,
        description="Timestamp (UTC) of the most recent post.",
    )
    instagram_has_catalog: bool | None = Field(
        default=None,
        description="True if the profile has an active product catalogue.",
    )

    # --- Classification ----------------------------------------------------

    category_raw: str | None = Field(
        default=None,
        description="Business category as labelled in the source.",
    )
    ciiu_code: str | None = Field(
        default=None,
        description="CIIU sector code, assigned by Step 2 — NOT scraped.",
    )

    # --- Metrics -----------------------------------------------------------

    rating: float | None = Field(
        default=None,
        description="Average star rating 0–5.",
        ge=0.0,
        le=5.0,
    )
    reviews_count: int | None = Field(
        default=None,
        description="Number of reviews backing the rating.",
        ge=0,
    )

    # --- Online presence ---------------------------------------------------

    website: str | None = Field(
        default=None,
        description="Business website URL.",
    )
    bio_text: str | None = Field(
        default=None,
        description="Free-text description or bio from the source.",
    )

    # --- Metadata ----------------------------------------------------------

    quality_flags: list[str] = Field(
        default_factory=list,
        description=(
            "Array of quality issue tags detected by the scraper or Step 2. "
            "See QualityFlag enum for valid values."
        ),
    )
    scraped_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC timestamp when the scraper collected this record.",
    )
    created_at: datetime | None = Field(
        default=None,
        description="DB insertion timestamp (set by DB default, leave None on insert).",
    )
    updated_at: datetime | None = Field(
        default=None,
        description="Last modification timestamp (set by DB trigger, leave None on insert).",
    )

    # --- Validators --------------------------------------------------------

    @field_validator("phone_e164")
    @classmethod
    def validate_phone_e164(cls, v: str | None) -> str | None:
        """Enforce +57XXXXXXXXXX format. Reject anything else that is not None."""
        if v is None:
            return v
        if not _PHONE_E164_RE.match(v):
            raise ValueError(f"phone_e164 must match +57 followed by 10 digits, got: '{v}'")
        return v

    @field_validator("city")
    @classmethod
    def validate_city(cls, v: str) -> str:
        """Only Medellín and Bogotá are in scope for this project."""
        if v not in _VALID_CITIES:
            raise ValueError(f"city must be one of {_VALID_CITIES}, got: '{v}'")
        return v

    @field_validator("instagram_handle")
    @classmethod
    def strip_at_sign(cls, v: str | None) -> str | None:
        """Strip leading '@' if scrapers include it."""
        if v is None:
            return v
        return v.lstrip("@")

    @field_validator("rating")
    @classmethod
    def validate_rating(cls, v: float | None) -> float | None:
        """Clamp rating to [0, 5] — redundant with Field bounds but explicit."""
        if v is None:
            return v
        if not 0.0 <= v <= 5.0:
            raise ValueError(f"rating must be between 0 and 5, got: {v}")
        return round(v, 1)

    @model_validator(mode="after")
    def auto_quality_flags(self) -> BusinessRaw:
        """
        Append quality flags for obviously missing critical fields.
        Scrapers may also add flags before validation.
        """
        flags: set[str] = set(self.quality_flags)
        if not self.phone_raw and not self.phone_e164:
            flags.add(QualityFlag.MISSING_PHONE.value)
        if not self.address_raw and not self.address_street:
            flags.add(QualityFlag.MISSING_ADDRESS.value)
        self.quality_flags = sorted(flags)
        return self


# ---------------------------------------------------------------------------
# Canonical model (post Step 2)
# ---------------------------------------------------------------------------


class BusinessCanonical(BusinessRaw):
    """
    One row in businesses_canonical — one row per resolved entity.

    Identical to BusinessRaw but master_id is REQUIRED (not optional).
    Only the Step 2 pipeline should instantiate this model.
    """

    master_id: UUID = Field(
        description=(
            "Required FK that groups all BusinessRaw rows for the same real-world entity. "
            "Assigned by entity-resolution in Step 2."
        ),
    )


# ---------------------------------------------------------------------------
# Convenience exports
# ---------------------------------------------------------------------------

__all__ = [
    "SourceName",
    "QualityFlag",
    "BusinessRaw",
    "BusinessCanonical",
]
